CREATE TABLE IF NOT EXISTS booking_status
(
    id   INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR             NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(255)                                        NOT NULL,
    email VARCHAR(512)                                        NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
    CONSTRAINT email_at CHECK ( email LIKE '%@%'),
    CONSTRAINT space_name_user CHECK ( name NOT LIKE ' ' and name NOT LIKE '')
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    description  VARCHAR(255)                                        not null,
    requester_id BIGINT                                              NOT NULL,
    CONSTRAINT "request_user_foreign" FOREIGN KEY (requester_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name         VARCHAR(255)                                        NOT NULL,
    description  VARCHAR(255)                                        NOT NULL,
    is_available BOOLEAN                                             NOT NULL,
    owner_id     BIGINT                                              NOT NULL,
    request_id   BIGINT,
    CONSTRAINT space_name_item CHECK ( name NOT LIKE ' ' and name NOT LIKE ''),
    CONSTRAINT "items_owner_foreign" FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT "items_request_foreign" FOREIGN KEY (request_id) REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS booking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    item_id    BIGINT                                              NOT NULL,
    booker_id  BIGINT                                              NOT NULL,
    status     INTEGER                                             NOT NULL,
    CONSTRAINT start_date_before CHECK ( start_date >= CURRENT_TIMESTAMP ),
    CONSTRAINT "booking_item_foreign" FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT "booking_booker_foreign" FOREIGN KEY (booker_id) REFERENCES users (id),
    CONSTRAINT "booking_status_foreign" FOREIGN KEY (status) REFERENCES booking_status (id)
)
